CREAT TABLE EMPRESA(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CNPJ CHAR(14) NOT NULL UNIQUE,
    DATA_FUNDAÇÃO DATE NOT NULL,
    NOME CHAR (8) NOT NULL,
    PRIMARY KEY(ID)
);

CREAT TABLE CLIENTES(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CNPJ C
)